<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="..\..\..\Utilities\Lombiq.Npm.Targets\Lombiq.Npm.Targets.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*;node_modules\**;Tests\**</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Walkthroughs for Orchard Core</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2023, Lombiq Technologies Ltd.</Copyright>
    <Description>Orchard Core module to teach you the fundamentals of using the CMS features with step-by-step guides. See the project website for detailed documentation.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Walkthroughs;Tutorial</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Walkthroughs</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Walkthroughs</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
    <None Remove="node_modules\**" />
    <None Remove="Tests\**" />
    <Vendor Include="node_modules/shepherd.js" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="2.1.0" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="2.1.0" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="2.1.0" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="2.1.0" />
    <PackageReference Include="OrchardCore.ContentFields" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
    <ProjectReference Include="..\..\..\Utilities\Lombiq.Npm.Targets\Lombiq.Npm.Targets.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries" Version="12.2.1-alpha.10.osoe-1069" />
    <PackageReference Include="Lombiq.Npm.Targets" Version="1.5.0" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="..\..\..\Utilities\Lombiq.Npm.Targets\Lombiq.Npm.Targets.targets" />

</Project>
